'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by SceneXamlCodeGenerator.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports Microsoft.Xna.Framework
Imports ProjectZ.Shared.Drawing
Imports ProjectZ.Shared.Drawing.UI
Imports ProjectZ.Shared.Drawing.UI.Input
Imports ProjectZ.Shared.Drawing.UI.Layout
Imports ProjectZ.Shared.Drawing.UI.Primitives
Imports ProjectZ.Shared.Drawing.Designer

Partial Public Class MainScene
    Inherits Scene

#Region "Designer Generated Fields"

    ' Main Panels
    Friend SidePanel As RectangleElement
    Friend PlayField As RectangleElement

    ' HUD Text Elements
    Friend EnemiesText As TextElement
    Friend LevelText As TextElement
    Friend CurrencyText As TextElement
    Friend HealthText As TextElement
    Friend TowerHintText As TextElement
    Friend NetworkModeText As TextElement

    ' Control Buttons
    Friend HostButton As Button
    Friend ClientButton As Button
    Friend StartButton As Button
    Friend StopButton As Button

    ' Tower Buttons (WithEvents for drag handlers)
    Friend WithEvents SpiralTowerButton As Button
    Friend WithEvents PointTowerButton As Button
    Friend WithEvents BurstTowerButton As Button
    Friend WithEvents RapidTowerButton As Button
    Friend WithEvents SniperTowerButton As Button
    Friend WithEvents BombButton As Button

    ' Tower Menu Elements
    Friend TowerMenuBackground As RectangleElement
    Friend TowerMenuTitle As TextElement
    Friend UpgradeButton As Button
    Friend SellButton As Button
    Friend TargetFirstButton As Button
    Friend TargetLastButton As Button
    Friend TargetClosestButton As Button
    Friend TargetStrongestButton As Button
    Friend TargetWeakestButton As Button
    Friend CloseMenuButton As Button

    ' Tooltip Elements
    Friend TooltipBackground As RectangleElement
    Friend TooltipText As TextElement

    ' Range Indicator
    Friend RangeIndicator As CircleElement

#End Region

#Region "Designer Generated Methods"

    ''' <summary>
    ''' Initializes UI elements from XAML definition.
    ''' This is called automatically by the designer-generated code.
    ''' </summary>
    Private Sub InitializeComponent()
        Dim parser As New SceneXamlParser(Me)
        Dim xamlContent As String = GetXamlContent()
        Dim root As SceneElement = parser.Parse(xamlContent)

        ' Add all top-level children to the scene
        For Each child As SceneElement In root.Children
            AddElement(child)
        Next

        ' Bind named elements to fields
        SidePanel = parser.FindName(Of RectangleElement)("SidePanel")
        PlayField = parser.FindName(Of RectangleElement)("PlayField")

        EnemiesText = parser.FindName(Of TextElement)("EnemiesText")
        LevelText = parser.FindName(Of TextElement)("LevelText")
        CurrencyText = parser.FindName(Of TextElement)("CurrencyText")
        HealthText = parser.FindName(Of TextElement)("HealthText")
        TowerHintText = parser.FindName(Of TextElement)("TowerHintText")
        NetworkModeText = parser.FindName(Of TextElement)("NetworkModeText")

        HostButton = parser.FindName(Of Button)("HostButton")
        ClientButton = parser.FindName(Of Button)("ClientButton")
        StartButton = parser.FindName(Of Button)("StartButton")
        StopButton = parser.FindName(Of Button)("StopButton")

        SpiralTowerButton = parser.FindName(Of Button)("SpiralTowerButton")
        PointTowerButton = parser.FindName(Of Button)("PointTowerButton")
        BurstTowerButton = parser.FindName(Of Button)("BurstTowerButton")
        RapidTowerButton = parser.FindName(Of Button)("RapidTowerButton")
        SniperTowerButton = parser.FindName(Of Button)("SniperTowerButton")
        BombButton = parser.FindName(Of Button)("BombButton")

        TowerMenuBackground = parser.FindName(Of RectangleElement)("TowerMenuBackground")
        TowerMenuTitle = parser.FindName(Of TextElement)("TowerMenuTitle")
        UpgradeButton = parser.FindName(Of Button)("UpgradeButton")
        SellButton = parser.FindName(Of Button)("SellButton")
        TargetFirstButton = parser.FindName(Of Button)("TargetFirstButton")
        TargetLastButton = parser.FindName(Of Button)("TargetLastButton")
        TargetClosestButton = parser.FindName(Of Button)("TargetClosestButton")
        TargetStrongestButton = parser.FindName(Of Button)("TargetStrongestButton")
        TargetWeakestButton = parser.FindName(Of Button)("TargetWeakestButton")
        CloseMenuButton = parser.FindName(Of Button)("CloseMenuButton")

        TooltipBackground = parser.FindName(Of RectangleElement)("TooltipBackground")
        TooltipText = parser.FindName(Of TextElement)("TooltipText")

        RangeIndicator = parser.FindName(Of CircleElement)("RangeIndicator")

        ' Apply runtime properties not specified in XAML
        ApplyRuntimeProperties()
    End Sub

    ''' <summary>
    ''' Applies runtime-specific properties that aren't suitable for XAML.
    ''' </summary>
    Private Sub ApplyRuntimeProperties()
        ' Panel properties
        SidePanel.isMovable = False
        SidePanel.OrientationReserve = DisplayReservation.ReserveX
        PlayField.isMovable = False

        ' Tower button movability
        SpiralTowerButton.isMovable = True
        PointTowerButton.isMovable = True
        BurstTowerButton.isMovable = True
        RapidTowerButton.isMovable = True
        SniperTowerButton.isMovable = True
        BombButton.isMovable = True

        ' Tooltip mouse bypass
        TooltipBackground.isMouseBypassEnabled = True
        TooltipText.isMouseBypassEnabled = True

        ' Range indicator properties
        RangeIndicator.isMovable = False
        RangeIndicator.isMouseBypassEnabled = True
        RangeIndicator.isVisible = False

        ' Tower menu properties
        TowerMenuBackground.isMovable = False
    End Sub

    ''' <summary>
    ''' Returns the embedded XAML content for this scene.
    ''' Override this method to load XAML from a different source.
    ''' </summary>
    Protected Overridable Function GetXamlContent() As String
        Return _xamlContent
    End Function

#End Region

#Region "Embedded XAML Content"

    Private Const _xamlContent As String =
        "<?xml version=""1.0"" encoding=""utf-8""?>" & vbCrLf &
        "<Scene xmlns=""http://projectz.shared.drawing""" & vbCrLf &
        "       xmlns:x=""http://schemas.microsoft.com/winfx/2006/xaml"">" & vbCrLf &
        "    " & vbCrLf &
        "    <RectangleElement x:Name=""SidePanel"" Background=""#161616"" Width=""220"" Height=""720"" X=""0"" Y=""0"" />" & vbCrLf &
        "    <RectangleElement x:Name=""PlayField"" Background=""#0C0C0C"" X=""220"" Y=""0"" Width=""1060"" Height=""720"" />" & vbCrLf &
        "    " & vbCrLf &
        "    <TextElement x:Name=""EnemiesText"" Text=""Enemies: 0"" Foreground=""White"" X=""16"" Y=""24"" />" & vbCrLf &
        "    <TextElement x:Name=""LevelText"" Text=""Level: 1"" Foreground=""White"" X=""16"" Y=""56"" />" & vbCrLf &
        "    <TextElement x:Name=""CurrencyText"" Text=""Currency: 0"" Foreground=""White"" X=""16"" Y=""88"" />" & vbCrLf &
        "    <TextElement x:Name=""HealthText"" Text=""Health: 0"" Foreground=""White"" X=""16"" Y=""120"" />" & vbCrLf &
        "    <TextElement x:Name=""TowerHintText"" Text=""Drag towers onto the map, click to upgrade"" Foreground=""LightGray"" X=""16"" Y=""160"" />" & vbCrLf &
        "    <TextElement x:Name=""NetworkModeText"" Text=""Mode: Host"" Foreground=""LightGray"" X=""16"" Y=""200"" />" & vbCrLf &
        "    " & vbCrLf &
        "    <Button x:Name=""HostButton"" Content=""Host"" Width=""180"" Height=""32"" X=""16"" Y=""230"" Background=""#323232"" />" & vbCrLf &
        "    <Button x:Name=""ClientButton"" Content=""Client"" Width=""180"" Height=""32"" X=""16"" Y=""270"" Background=""#323232"" />" & vbCrLf &
        "    <Button x:Name=""StartButton"" Content=""Start"" Width=""180"" Height=""32"" X=""16"" Y=""330"" Background=""#323232"" />" & vbCrLf &
        "    <Button x:Name=""StopButton"" Content=""Stop"" Width=""180"" Height=""32"" X=""16"" Y=""370"" Background=""#323232"" />" & vbCrLf &
        "    " & vbCrLf &
        "    <Button x:Name=""SpiralTowerButton"" Content=""Spiral"" Width=""180"" Height=""32"" X=""16"" Y=""430"" Background=""#323232"" />" & vbCrLf &
        "    <Button x:Name=""PointTowerButton"" Content=""Point"" Width=""180"" Height=""32"" X=""16"" Y=""470"" Background=""#323232"" />" & vbCrLf &
        "    <Button x:Name=""BurstTowerButton"" Content=""Burst"" Width=""180"" Height=""32"" X=""16"" Y=""510"" Background=""#323232"" />" & vbCrLf &
        "    <Button x:Name=""RapidTowerButton"" Content=""Rapid"" Width=""180"" Height=""32"" X=""16"" Y=""550"" Background=""#323232"" />" & vbCrLf &
        "    <Button x:Name=""SniperTowerButton"" Content=""Sniper"" Width=""180"" Height=""32"" X=""16"" Y=""590"" Background=""#323232"" />" & vbCrLf &
        "    <Button x:Name=""BombButton"" Content=""Bomb ($5)"" Width=""180"" Height=""32"" X=""16"" Y=""640"" Background=""#323232"" />" & vbCrLf &
        "    " & vbCrLf &
        "    <RectangleElement x:Name=""TowerMenuBackground"" Background=""#282828F0"" Width=""160"" Height=""200"" X=""-1000"" Y=""-1000"" />" & vbCrLf &
        "    <TextElement x:Name=""TowerMenuTitle"" Text=""Tower Menu"" Foreground=""White"" X=""-1000"" Y=""-1000"" />" & vbCrLf &
        "    <Button x:Name=""UpgradeButton"" Content=""Upgrade"" Width=""140"" Height=""28"" X=""-1000"" Y=""-1000"" Background=""#323232"" />" & vbCrLf &
        "    <Button x:Name=""SellButton"" Content=""Sell"" Width=""140"" Height=""28"" X=""-1000"" Y=""-1000"" Background=""#323232"" />" & vbCrLf &
        "    <Button x:Name=""TargetFirstButton"" Content=""First"" Width=""65"" Height=""24"" X=""-1000"" Y=""-1000"" Background=""#3C3C3C"" />" & vbCrLf &
        "    <Button x:Name=""TargetLastButton"" Content=""Last"" Width=""65"" Height=""24"" X=""-1000"" Y=""-1000"" Background=""#3C3C3C"" />" & vbCrLf &
        "    <Button x:Name=""TargetClosestButton"" Content=""Closest"" Width=""65"" Height=""24"" X=""-1000"" Y=""-1000"" Background=""#3C3C3C"" />" & vbCrLf &
        "    <Button x:Name=""TargetStrongestButton"" Content=""Strong"" Width=""65"" Height=""24"" X=""-1000"" Y=""-1000"" Background=""#3C3C3C"" />" & vbCrLf &
        "    <Button x:Name=""TargetWeakestButton"" Content=""Weak"" Width=""65"" Height=""24"" X=""-1000"" Y=""-1000"" Background=""#3C3C3C"" />" & vbCrLf &
        "    <Button x:Name=""CloseMenuButton"" Content=""X"" Width=""24"" Height=""24"" X=""-1000"" Y=""-1000"" Background=""#323232"" />" & vbCrLf &
        "    " & vbCrLf &
        "    <RectangleElement x:Name=""TooltipBackground"" Background=""#1E1E1EE6"" Width=""200"" Height=""80"" X=""-1000"" Y=""-1000"" />" & vbCrLf &
        "    <TextElement x:Name=""TooltipText"" Text="""" Foreground=""White"" X=""-1000"" Y=""-1000"" />" & vbCrLf &
        "    " & vbCrLf &
        "    <CircleElement x:Name=""RangeIndicator"" Fill=""#64C8643C"" Width=""100"" Height=""100"" X=""-1000"" Y=""-1000"" Visibility=""Hidden"" />" & vbCrLf &
        "    " & vbCrLf &
        "</Scene>"

#End Region

End Class
